### ISSUE TITLE
To-do next:

### ISSUE THREAD

**Issue by pciang** [DroidCare/DroidCare#1]
**Fri, 27 Feb 2015**
* [X] clean Global.java code

**Sat, 28 Feb 2015**
* [x] Convert AppointmentManager to a Singleton class
* [x] Retrieve appointment list through POST request

**Target: Thurs, 4 Mar 2015**
* [x] Refactoring login and logout logic -> put into LoginManager
* [x] Refactoring user profile update logic -> put into UserManager

**Target: Sat, 7 Mar 2015**
* [x] Browse, encode, decode image

**TARGET**
* [x] View appointment details consultant layout (Accept / Decline)
* [x] Handle accept / decline appointment logic (use CosultantAppointmentManager)
* [x] New appointment form
* [x] Edit appointment (patient) form (use PatientAppointmentManager to handle the database updating)
* [x] View appointment details patient layout (Edit / Cancel)
* [x] Handle cancel appointment logic (use PatientAppointmentManager)
* [x] Forget password

**Comment by edwin-candinegara** [comment]
@pciang : please follow the plan above and tick whatever we've done along the way

**Comment by pciang** [comment]
Project done!
